ALTER TABLE DRY_STOCK
ADD FOREIGN KEY  (REP_NUM) REFERENCES VENDORS(REP_NUM);

ALTER TABLE CURRENT_LIVE
ADD FOREIGN KEY (LIVESTOCK_ID) REFERENCES MASTER_LIVE(LIVESTOCK_ID);

ALTER TABLE CURRENT_LIVE
ADD FOREIGN KEY (REP_NUM) REFERENCES VENDORS(REP_NUM);

ALTER TABLE ORDER_LINE
ADD FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID);

ALTER TABLE ORDER_LINE
ADD FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMP_ID);

ALTER TABLE ORDER_LINE
ADD FOREIGN KEY (ITEM_ID) REFERENCES DRY_STOCK(DRY_STOCK_ID);

ALTER TABLE ORDER_LINE
ADD FOREIGN KEY (ITEM_ID) REFERENCES MASTER_LIVE(LIVESTOCK_ID);
