USE DEEP_SEA;

DROP TABLE IF EXISTS MASTER_LIVE;
CREATE TABLE MASTER_LIVE
(ID CHAR(7) NOT NULL PRIMARY KEY,
SCI_NAME CHAR(18),
COM_NAME CHAR(18),
WTR_TYPE CHAR(6),
TEMPERATURE CHAR(7),
TEMPERMENT CHAR(6),
PH CHAR(5),
SIZE CHAR(5),
LIGHT_LEVEL CHAR(3));

DROP TABLE IF EXISTS DRY_STOCK;
CREATE TABLE DRY_STOCK
(DESC CHAR(10) NOT NULL,
IN_STOCK CHAR(3),
QUOTED_PRICE DECIMAL(5,2),
SHELF_LOC CHAR(5),
REP_NUM CHAR(3));

DROP TABLE IF EXISTS CURRENT_LIVE;
CREATE TABLE CURRENT_LIVE
(ID CHAR(7) NOT NULL PRIMARY KEY,
SCI_NAME CHAR(18),
COM_NAME CHAR(18),
WTR_TYPE CHAR(6),
TEMPERATURE CHAR(7),
TEMPERAMENT CHAR(6),
PH CHAR(5),
SIZE CHAR(5),
LIGHT_LEVEL CHAR(3));

DROP TABLE IF EXISTS VENDORS;
CREATE TABLE VENDORS
(REP_NUM CHAR(3) NOT NULL PRIMARY KEY,
REP_NAME CHAR(16),
REP_PHONE CHAR(12));

DROP TABLE IF EXISTS ORDERS;
CREATE TALBE ORDERS
(ORDER_ID CHAR(4) NOT NULL PRIMARY KEY,
ORDER_DATE DATE,
ORDER_TOTAL DECIMAL(8,2));

DROP TABLE IF EXISTS ORDER_LINE;
(ORDER_ID CHAR(4) NOT NULL PRIMARY KEY,
EMP_IT CHAR(3),
DESC CHAR(18),
PAID_PRICE(7,2));

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES
(EMP_ID CHAR(3) NOT NULL PRIMARY KEY,
LAST_NAME CHAR(10),
FIRST_NAME CHAR(10),
ADDRESS CHAR(18),
CITY CHAR(10),
ZIP CHAR(6),
POSITION CHAR(10),
HOURLY_RATE DECIMAL(3,2));
