SELECT  MASTER_LIVESTOCK.COM_NAME AS 'NAME', CURRENT_LIVESTOCK.IN_STOCK FROM MASTER_LIVESTOCK, CURRENT_LIVESTOCK 
WHERE CURRENT_LIVESTOCK.CURRENT_LIVESTOCK_ID = MASTER_LIVESTOCK.MASTER_LIVESTOCK_ID
AND MASTER_LIVESTOCK.WTR_TYPE = 'FRESH';

SELECT SUM(IN_STOCK) AS 'TOTAL FRESHWATER FISH' FROM CURRENT_LIVESTOCK, MASTER_LIVESTOCK WHERE WTR_TYPE = 'FRESH' AND
CURRENT_LIVESTOCK_ID = MASTER_LIVESTOCK_ID;

SELECT  CURRENT_LIVESTOCK.IN_STOCK FROM MASTER_LIVESTOCK, CURRENT_LIVESTOCK 
WHERE CURRENT_LIVESTOCK.CURRENT_LIVESTOCK_ID = MASTER_LIVESTOCK.MASTER_LIVESTOCK_ID
AND MASTER_LIVESTOCK.WTR_TYPE != 'FRESH';

Select SUM(IN_STOCK * QUOTED_PRICE) AS 'TOTAL DRY STOCK VALUE' FROM DRY_STOCK;

ALTER TABLE VENDORS ADD REP_ADDRESS CHAR(25);
ALTER TABLE VENDORS ADD REP_ZIP CHAR(6);
ALTER TABLE VENDORS ADD REP_COUNTRY CHAR(25);

UPDATE VENDORS SET REP_ADDRESS = '65112 Grape drv',   REP_ZIP = '48316', REP_COUNTRY = 'USA' WHERE REP_NUM = '1';
UPDATE VENDORS SET REP_ADDRESS = '12473 Orange lane', REP_ZIP = '79134', REP_COUNTRY = 'USA' WHERE REP_NUM = '2';
UPDATE VENDORS SET REP_ADDRESS = '67216 Grape drv',   REP_ZIP = '54598', REP_COUNTRY = 'USA' WHERE REP_NUM = '3';